<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>PDF_Report_Final</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="fo-dicom" Version="5.2.5" />
    <PackageReference Include="iTextSharp" Version="5.5.13.4" />
    <PackageReference Include="QuestPDF" Version="2025.12.1" />
    <PackageReference Include="ScottPlot" Version="5.1.57" />
    <PackageReference Include="System.Drawing.Common" Version="10.0.1" />
  </ItemGroup>

</Project>
